/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

/**
 *
 * @author Isaac's PC
 */
public class Informacion extends javax.swing.JFrame {
    int xMouse, yMouse; 
 
    public Informacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_cierre = new javax.swing.JPanel();
        JL_cierre = new javax.swing.JLabel();
        p_barra = new javax.swing.JPanel();
        JP_DERECHO = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        JL_INFO1 = new javax.swing.JLabel();
        JT_texto = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        JP_IZQUIERDO = new javax.swing.JPanel();
        JL_logo = new javax.swing.JLabel();
        JL_INFO = new javax.swing.JLabel();
        JS_1 = new javax.swing.JSeparator();
        JL_USUARIOS = new javax.swing.JLabel();
        JS_2 = new javax.swing.JSeparator();
        JL_EQUIPO = new javax.swing.JLabel();
        JL_UPI = new javax.swing.JLabel();
        JL_IPN = new javax.swing.JLabel();
        JL_SALIR = new javax.swing.JLabel();
        JS_3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(950, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_cierre.setBackground(new java.awt.Color(0, 0, 0));

        JL_cierre.setBackground(new java.awt.Color(236, 234, 228));
        JL_cierre.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        JL_cierre.setForeground(new java.awt.Color(255, 255, 255));
        JL_cierre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_cierre.setText("X");
        JL_cierre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_cierreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JL_cierreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JL_cierreMouseExited(evt);
            }
        });

        javax.swing.GroupLayout p_cierreLayout = new javax.swing.GroupLayout(p_cierre);
        p_cierre.setLayout(p_cierreLayout);
        p_cierreLayout.setHorizontalGroup(
            p_cierreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JL_cierre, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        p_cierreLayout.setVerticalGroup(
            p_cierreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JL_cierre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(p_cierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 20));

        p_barra.setBackground(new java.awt.Color(0, 0, 0));
        p_barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                p_barraMouseDragged(evt);
            }
        });
        p_barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                p_barraMousePressed(evt);
            }
        });

        javax.swing.GroupLayout p_barraLayout = new javax.swing.GroupLayout(p_barra);
        p_barra.setLayout(p_barraLayout);
        p_barraLayout.setHorizontalGroup(
            p_barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        p_barraLayout.setVerticalGroup(
            p_barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(p_barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 900, 20));

        JP_DERECHO.setBackground(new java.awt.Color(158, 189, 197));

        jPanel1.setBackground(new java.awt.Color(236, 234, 228));

        JL_INFO1.setBackground(new java.awt.Color(255, 255, 255));
        JL_INFO1.setFont(new java.awt.Font("Roboto Medium", 0, 30)); // NOI18N
        JL_INFO1.setForeground(new java.awt.Color(255, 0, 51));
        JL_INFO1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_INFO1.setText("INFORMACIÓN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(JL_INFO1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JL_INFO1)
                .addContainerGap())
        );

        JT_texto.setEditable(false);
        JT_texto.setBackground(new java.awt.Color(158, 189, 197));
        JT_texto.setColumns(20);
        JT_texto.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        JT_texto.setRows(5);
        JT_texto.setText("\n\n   EN MECATENA, EMPRESA FUNDADA EN 1984, NOS HEMOS DEDICADO\n   DESDE NUESTROS INICIOS A LA COMERCIALIZACIÓN Y SOPORTE \n   TÉCNICO DE PRODUCTOS OFIMÁTICOS, ESPECIALIZÁNDONOS EN \n   SOLUCIONES GLOBALES. \n\n   DICHAS SOLUCIONES SON POSIBLES TENIENDO EN CUENTA LA \n   DIVERSIDAD DE PRODUCTOS QUE COMERCIALIZAMOS A TRAVÉS DE\n   DISTINTAS DIVISIONES: MOBILIARIO, HARDWARE, SOFTWARE, \n   PERIFÉRICOS INFORMÁTICOS, MULTIMEDIA, SOLUCIONES DE\n   TELECOMUNICACIÓN, SISTEMAS DE REPRODUCCIÓN DE COPIAS,\n   ASESORAMIENTO, ETC.\n");
        JT_texto.setAutoscrolls(false);
        JT_texto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JT_texto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JT_texto.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cubo_mini.png"))); // NOI18N

        javax.swing.GroupLayout JP_DERECHOLayout = new javax.swing.GroupLayout(JP_DERECHO);
        JP_DERECHO.setLayout(JP_DERECHOLayout);
        JP_DERECHOLayout.setHorizontalGroup(
            JP_DERECHOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JP_DERECHOLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(JP_DERECHOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JT_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        JP_DERECHOLayout.setVerticalGroup(
            JP_DERECHOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_DERECHOLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JT_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        getContentPane().add(JP_DERECHO, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 700, 600));

        JP_IZQUIERDO.setBackground(new java.awt.Color(236, 234, 228));

        JL_logo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JL_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N

        JL_INFO.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        JL_INFO.setForeground(new java.awt.Color(255, 0, 51));
        JL_INFO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_INFO.setText("Información");
        JL_INFO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_INFOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JL_INFOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JL_INFOMouseExited(evt);
            }
        });

        JL_USUARIOS.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        JL_USUARIOS.setForeground(new java.awt.Color(0, 0, 0));
        JL_USUARIOS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_USUARIOS.setText("Usuarios");
        JL_USUARIOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_USUARIOSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JL_USUARIOSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JL_USUARIOSMouseExited(evt);
            }
        });

        JL_EQUIPO.setFont(new java.awt.Font("Roboto Light", 2, 11)); // NOI18N
        JL_EQUIPO.setForeground(new java.awt.Color(102, 102, 102));
        JL_EQUIPO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_EQUIPO.setText("KAREN OLVERA & ISAAC PÉREZ");

        JL_UPI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/upi.png"))); // NOI18N
        JL_UPI.setMaximumSize(new java.awt.Dimension(75, 90));
        JL_UPI.setMinimumSize(new java.awt.Dimension(75, 90));
        JL_UPI.setPreferredSize(new java.awt.Dimension(75, 90));

        JL_IPN.setForeground(new java.awt.Color(0, 0, 0));
        JL_IPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/poli.png"))); // NOI18N

        JL_SALIR.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        JL_SALIR.setForeground(new java.awt.Color(0, 0, 0));
        JL_SALIR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_SALIR.setText("Salir");
        JL_SALIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_SALIRMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JL_SALIRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JL_SALIRMouseExited(evt);
            }
        });

        javax.swing.GroupLayout JP_IZQUIERDOLayout = new javax.swing.GroupLayout(JP_IZQUIERDO);
        JP_IZQUIERDO.setLayout(JP_IZQUIERDOLayout);
        JP_IZQUIERDOLayout.setHorizontalGroup(
            JP_IZQUIERDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_IZQUIERDOLayout.createSequentialGroup()
                .addGroup(JP_IZQUIERDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_IZQUIERDOLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JL_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JP_IZQUIERDOLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(JS_1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JP_IZQUIERDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JP_IZQUIERDOLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(JL_SALIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(JL_EQUIPO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JP_IZQUIERDOLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(JP_IZQUIERDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(JP_IZQUIERDOLayout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(JL_IPN)
                                    .addGap(35, 35, 35)
                                    .addComponent(JL_UPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(JP_IZQUIERDOLayout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(JS_2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(JL_INFO, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JL_USUARIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(JP_IZQUIERDOLayout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(JS_3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        JP_IZQUIERDOLayout.setVerticalGroup(
            JP_IZQUIERDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_IZQUIERDOLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(JL_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(JL_INFO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JS_1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(JL_USUARIOS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JS_2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(JL_SALIR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JS_3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(JP_IZQUIERDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JL_IPN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_UPI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JL_EQUIPO, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        getContentPane().add(JP_IZQUIERDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JL_cierreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_cierreMouseClicked
        System.exit(0);
    }//GEN-LAST:event_JL_cierreMouseClicked

    private void JL_cierreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_cierreMouseEntered
        p_cierre.setBackground(java.awt.Color.RED);
        JL_cierre.setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_JL_cierreMouseEntered

    private void JL_cierreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_cierreMouseExited
        //p_cierre.setBackground(new java.awt.Color(236, 234, 228, 255));
        p_cierre.setBackground(java.awt.Color.BLACK);
        JL_cierre.setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_JL_cierreMouseExited

    private void p_barraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_barraMouseDragged
        int x= evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_p_barraMouseDragged

    private void p_barraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_barraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_p_barraMousePressed

    private void JL_INFOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_INFOMouseClicked
        Informacion cambio = new Informacion(); 
            cambio.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_JL_INFOMouseClicked

    private void JL_INFOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_INFOMouseEntered
        JL_INFO.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_JL_INFOMouseEntered

    private void JL_INFOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_INFOMouseExited
        JL_INFO.setForeground(java.awt.Color.RED);
    }//GEN-LAST:event_JL_INFOMouseExited

    private void JL_USUARIOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_USUARIOSMouseClicked
        Usuarios cambio2 = new Usuarios(); 
            cambio2.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_JL_USUARIOSMouseClicked

    private void JL_USUARIOSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_USUARIOSMouseEntered
        JL_USUARIOS.setForeground(java.awt.Color.RED);
    }//GEN-LAST:event_JL_USUARIOSMouseEntered

    private void JL_USUARIOSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_USUARIOSMouseExited
        JL_USUARIOS.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_JL_USUARIOSMouseExited

    private void JL_SALIRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_SALIRMouseClicked
        Login cambioL = new Login(); 
            cambioL.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_JL_SALIRMouseClicked

    private void JL_SALIRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_SALIRMouseEntered
        JL_SALIR.setForeground(java.awt.Color.RED);
    }//GEN-LAST:event_JL_SALIRMouseEntered

    private void JL_SALIRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_SALIRMouseExited
        JL_SALIR.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_JL_SALIRMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL_EQUIPO;
    private javax.swing.JLabel JL_INFO;
    private javax.swing.JLabel JL_INFO1;
    private javax.swing.JLabel JL_IPN;
    private javax.swing.JLabel JL_SALIR;
    private javax.swing.JLabel JL_UPI;
    private javax.swing.JLabel JL_USUARIOS;
    private javax.swing.JLabel JL_cierre;
    private javax.swing.JLabel JL_logo;
    private javax.swing.JPanel JP_DERECHO;
    private javax.swing.JPanel JP_IZQUIERDO;
    private javax.swing.JSeparator JS_1;
    private javax.swing.JSeparator JS_2;
    private javax.swing.JSeparator JS_3;
    private javax.swing.JTextArea JT_texto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel p_barra;
    private javax.swing.JPanel p_cierre;
    // End of variables declaration//GEN-END:variables
}
