
package login;

import com.sun.prism.paint.Color;
import javax.swing.*;

public class Login extends javax.swing.JFrame {
    int xMouse, yMouse; 
     
    
    public Login() {
        initComponents();
        
        //Color Crema = new Color(128,100,100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_fondo = new javax.swing.JPanel();
        p_cierre = new javax.swing.JPanel();
        JL_cierre = new javax.swing.JLabel();
        p_barra = new javax.swing.JPanel();
        JL_cubo = new javax.swing.JLabel();
        JL_fondo_der = new javax.swing.JLabel();
        JL_nombre = new javax.swing.JLabel();
        JL_nombre2 = new javax.swing.JLabel();
        p_izquierdo = new javax.swing.JPanel();
        p_derecho = new javax.swing.JPanel();
        JL_logo = new javax.swing.JLabel();
        JL_titulo = new javax.swing.JLabel();
        JL_usuario = new javax.swing.JLabel();
        separator1 = new javax.swing.JSeparator();
        txt_usuario = new javax.swing.JTextField();
        JL_contra = new javax.swing.JLabel();
        JL_recuperacion = new javax.swing.JLabel();
        separator2 = new javax.swing.JSeparator();
        JP_contra = new javax.swing.JPasswordField();
        p_boton = new javax.swing.JPanel();
        JL_boton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        p_fondo.setBackground(new java.awt.Color(255, 102, 102));
        p_fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_cierre.setBackground(new java.awt.Color(0, 0, 0));

        JL_cierre.setBackground(new java.awt.Color(236, 234, 228));
        JL_cierre.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        JL_cierre.setForeground(new java.awt.Color(255, 255, 255));
        JL_cierre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_cierre.setText("X");
        JL_cierre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_cierreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JL_cierreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JL_cierreMouseExited(evt);
            }
        });

        javax.swing.GroupLayout p_cierreLayout = new javax.swing.GroupLayout(p_cierre);
        p_cierre.setLayout(p_cierreLayout);
        p_cierreLayout.setHorizontalGroup(
            p_cierreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JL_cierre, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        p_cierreLayout.setVerticalGroup(
            p_cierreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JL_cierre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        p_fondo.add(p_cierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 20));

        p_barra.setBackground(new java.awt.Color(0, 0, 0));
        p_barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                p_barraMouseDragged(evt);
            }
        });
        p_barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                p_barraMousePressed(evt);
            }
        });

        javax.swing.GroupLayout p_barraLayout = new javax.swing.GroupLayout(p_barra);
        p_barra.setLayout(p_barraLayout);
        p_barraLayout.setHorizontalGroup(
            p_barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        p_barraLayout.setVerticalGroup(
            p_barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        p_fondo.add(p_barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 900, 20));

        JL_cubo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_cubo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cubo_mediano.png"))); // NOI18N
        p_fondo.add(JL_cubo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 430, 320));

        JL_fondo_der.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_fondo_der.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        p_fondo.add(JL_fondo_der, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 430, 600));

        JL_nombre.setFont(new java.awt.Font("Stop", 1, 60)); // NOI18N
        JL_nombre.setForeground(new java.awt.Color(255, 0, 51));
        JL_nombre.setText("MECATENA");
        p_fondo.add(JL_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, -1, -1));

        JL_nombre2.setBackground(new java.awt.Color(255, 255, 255));
        JL_nombre2.setFont(new java.awt.Font("Nioc Tresni", 0, 48)); // NOI18N
        JL_nombre2.setForeground(new java.awt.Color(255, 255, 255));
        JL_nombre2.setText("software");
        p_fondo.add(JL_nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, -1, -1));

        p_izquierdo.setBackground(new java.awt.Color(158, 189, 197));

        javax.swing.GroupLayout p_izquierdoLayout = new javax.swing.GroupLayout(p_izquierdo);
        p_izquierdo.setLayout(p_izquierdoLayout);
        p_izquierdoLayout.setHorizontalGroup(
            p_izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        p_izquierdoLayout.setVerticalGroup(
            p_izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        p_fondo.add(p_izquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 430, 600));

        p_derecho.setBackground(new java.awt.Color(236, 234, 228));
        p_derecho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JL_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cubo_mini.png"))); // NOI18N
        p_derecho.add(JL_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 70));

        JL_titulo.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        JL_titulo.setForeground(new java.awt.Color(0, 0, 0));
        JL_titulo.setText("INICIO DE SESIÓN");
        p_derecho.add(JL_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        JL_usuario.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        JL_usuario.setForeground(new java.awt.Color(0, 0, 0));
        JL_usuario.setText("Usuario");
        p_derecho.add(JL_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));
        p_derecho.add(separator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 430, 20));

        txt_usuario.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(204, 204, 204));
        txt_usuario.setText("Ingrese su nombre de usuario");
        txt_usuario.setAlignmentX(0.0F);
        txt_usuario.setAlignmentY(0.0F);
        txt_usuario.setBorder(null);
        txt_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_usuarioMousePressed(evt);
            }
        });
        p_derecho.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 430, 40));

        JL_contra.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        JL_contra.setForeground(new java.awt.Color(0, 0, 0));
        JL_contra.setText("Contraseña");
        p_derecho.add(JL_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        JL_recuperacion.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        JL_recuperacion.setForeground(new java.awt.Color(255, 0, 0));
        JL_recuperacion.setText("¿Olvidaste tu contraseña?");
        JL_recuperacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_recuperacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JL_recuperacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JL_recuperacionMouseExited(evt);
            }
        });
        p_derecho.add(JL_recuperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));
        p_derecho.add(separator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 429, 11));

        JP_contra.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        JP_contra.setForeground(new java.awt.Color(204, 204, 204));
        JP_contra.setText("**********");
        JP_contra.setBorder(null);
        JP_contra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JP_contraMousePressed(evt);
            }
        });
        p_derecho.add(JP_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 429, 44));

        p_boton.setBackground(new java.awt.Color(255, 0, 51));

        JL_boton.setBackground(new java.awt.Color(158, 189, 197));
        JL_boton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JL_boton.setForeground(new java.awt.Color(255, 255, 255));
        JL_boton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_boton.setText("INGRESAR");
        JL_boton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.lightGray, java.awt.Color.lightGray));
        JL_boton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JL_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_botonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JL_botonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JL_botonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout p_botonLayout = new javax.swing.GroupLayout(p_boton);
        p_boton.setLayout(p_botonLayout);
        p_botonLayout.setHorizontalGroup(
            p_botonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JL_boton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
        );
        p_botonLayout.setVerticalGroup(
            p_botonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_botonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JL_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        p_derecho.add(p_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        p_fondo.add(p_derecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 520, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p_barraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_barraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY(); 
    }//GEN-LAST:event_p_barraMousePressed

    private void p_barraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_barraMouseDragged
        int x= evt.getXOnScreen();
        int y = evt.getYOnScreen(); 
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_p_barraMouseDragged

    private void JL_cierreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_cierreMouseClicked
        System.exit(0);
    }//GEN-LAST:event_JL_cierreMouseClicked

    private void JL_cierreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_cierreMouseEntered
        p_cierre.setBackground(java.awt.Color.RED);
        JL_cierre.setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_JL_cierreMouseEntered

    private void JL_cierreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_cierreMouseExited
        //p_cierre.setBackground(new java.awt.Color(236, 234, 228, 255));
        p_cierre.setBackground(java.awt.Color.BLACK);
        JL_cierre.setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_JL_cierreMouseExited

    private void JL_botonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_botonMouseClicked
        //VALIDACION campos vacios
        if(txt_usuario.getText().equals("Ingrese su nombre de usuario") 
                || String.valueOf(JP_contra.getPassword()).equals("**********") || 
                txt_usuario.getText().isEmpty() || String.valueOf(JP_contra.getPassword()).isEmpty()){
            
            JOptionPane.showMessageDialog(this, "DEBES INGRESAR USUARIO Y CONTRASEÑA");
            
        }else if(txt_usuario.getText().equals("root") && String.valueOf(JP_contra.getPassword()).equals("123")){
            Informacion cambio = new Informacion(); 
            cambio.setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(this, "USUARIO O CONTRASEÑA INCORRECTOS");
        }
       
        //a la otra vista
           
    }//GEN-LAST:event_JL_botonMouseClicked

    private void JL_botonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_botonMouseEntered
        p_boton.setBackground(new java.awt.Color(158,189,197,255));
        JL_boton.setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_JL_botonMouseEntered

    private void JL_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_botonMouseExited
        p_boton.setBackground(java.awt.Color.red);
        JL_boton.setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_JL_botonMouseExited

    private void txt_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usuarioMousePressed
        if(txt_usuario.getText().equals("Ingrese su nombre de usuario")){
            txt_usuario.setText("");
            txt_usuario.setForeground(java.awt.Color.black);
        }
        if(String.valueOf(JP_contra.getPassword()).isEmpty()){
           JP_contra.setText("**********");
           JP_contra.setForeground(java.awt.Color.gray); 
        }
    }//GEN-LAST:event_txt_usuarioMousePressed

    private void JP_contraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_contraMousePressed
        if(String.valueOf(JP_contra.getPassword()).equals("**********")){
           JP_contra.setText("");
           JP_contra.setForeground(java.awt.Color.black);
        }
        
        if(txt_usuario.getText().isEmpty()){
           txt_usuario.setText("Ingrese su nombre de usuario");
           txt_usuario.setForeground(java.awt.Color.gray);
        }
        
        
        
    }//GEN-LAST:event_JP_contraMousePressed

    private void JL_recuperacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_recuperacionMouseEntered
            JL_recuperacion.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_JL_recuperacionMouseEntered

    private void JL_recuperacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_recuperacionMouseExited
            JL_recuperacion.setForeground(java.awt.Color.RED);
    }//GEN-LAST:event_JL_recuperacionMouseExited

    private void JL_recuperacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_recuperacionMouseClicked
        JOptionPane.showMessageDialog(this, "Proceso de recuperación de contraseña");
    }//GEN-LAST:event_JL_recuperacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL_boton;
    private javax.swing.JLabel JL_cierre;
    private javax.swing.JLabel JL_contra;
    private javax.swing.JLabel JL_cubo;
    private javax.swing.JLabel JL_fondo_der;
    private javax.swing.JLabel JL_logo;
    private javax.swing.JLabel JL_nombre;
    private javax.swing.JLabel JL_nombre2;
    private javax.swing.JLabel JL_recuperacion;
    private javax.swing.JLabel JL_titulo;
    private javax.swing.JLabel JL_usuario;
    private javax.swing.JPasswordField JP_contra;
    private javax.swing.JPanel p_barra;
    private javax.swing.JPanel p_boton;
    private javax.swing.JPanel p_cierre;
    private javax.swing.JPanel p_derecho;
    private javax.swing.JPanel p_fondo;
    private javax.swing.JPanel p_izquierdo;
    private javax.swing.JSeparator separator1;
    private javax.swing.JSeparator separator2;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
