/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import Clases.Conexion;
import java.sql.*;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Isaac's PC
 */
public class Usuarios extends javax.swing.JFrame {
    int xMouse, yMouse;
   
    DefaultTableModel tabla = new DefaultTableModel(); 
    
    public Usuarios() {
        initComponents();
        //Rellenado de tabla
        try{
            //rutaynombreBD/nombreUsuarioBD/contraseñaBD
            Connection cn = Conexion.conectar(); 
            PreparedStatement pst = cn.prepareStatement("select ID, Cantidad, Tipo, Descripcion, PrecioU, Importe from productos");
            ResultSet rs = pst.executeQuery(); 
            
            //estableccemos la tabla y la colocamos dentro de un scroll
            JT_productos = new JTable(tabla); 
            JS_tabla.setViewportView(JT_productos);
            
            //establecemos las columnas 
            tabla.addColumn("ID");
            tabla.addColumn("Cantidad");
            tabla.addColumn("Tipo");
            tabla.addColumn("Descripcion");
            tabla.addColumn("PrecioU");
            tabla.addColumn("Importe");
            
            //mientras encuentre concidencias que repita el proceso
            while(rs.next()){
                //tipo object asi lo requiere la tabla
                Object[] fila = new Object[6];
                //for para rellenar las filas
                for(int i=0; i<6; i++){
                    fila[i] = rs.getObject(i + 1); 
                }
                tabla.addRow(fila);
            }
            cn.close();
            
        }catch(SQLException e){
            System.err.print("Error al llenar tabla!");
            JOptionPane.showMessageDialog(this, "Error al mostrar la información!");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_cierre = new javax.swing.JPanel();
        JL_cierre = new javax.swing.JLabel();
        p_barra = new javax.swing.JPanel();
        JP_DERECHO = new javax.swing.JPanel();
        JP_TITULO = new javax.swing.JPanel();
        JL_INFO1 = new javax.swing.JLabel();
        JL_CANTIDAD = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        JL_TIPO = new javax.swing.JLabel();
        txt_tipo = new javax.swing.JTextField();
        JL_DESCRIPCION = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        JL_PRECIO = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        JL_IMPORTE = new javax.swing.JLabel();
        txt_importe = new javax.swing.JTextField();
        jb_registro = new javax.swing.JButton();
        jb_modificar = new javax.swing.JButton();
        jb_eliminar = new javax.swing.JButton();
        JL_BUSCAR = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        jb_buscar = new javax.swing.JButton();
        jb_limpiar = new javax.swing.JButton();
        JS_tabla = new javax.swing.JScrollPane();
        JT_productos = new javax.swing.JTable();
        JP_IZQUIERDO = new javax.swing.JPanel();
        JL_logo = new javax.swing.JLabel();
        JL_INFO = new javax.swing.JLabel();
        JS_1 = new javax.swing.JSeparator();
        JL_USUARIOS = new javax.swing.JLabel();
        JS_2 = new javax.swing.JSeparator();
        JL_EQUIPO = new javax.swing.JLabel();
        JL_UPI = new javax.swing.JLabel();
        JL_IPN = new javax.swing.JLabel();
        JL_SALIR = new javax.swing.JLabel();
        JS_3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_cierre.setBackground(new java.awt.Color(0, 0, 0));

        JL_cierre.setBackground(new java.awt.Color(236, 234, 228));
        JL_cierre.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        JL_cierre.setForeground(new java.awt.Color(255, 255, 255));
        JL_cierre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_cierre.setText("X");
        JL_cierre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_cierreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JL_cierreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JL_cierreMouseExited(evt);
            }
        });

        javax.swing.GroupLayout p_cierreLayout = new javax.swing.GroupLayout(p_cierre);
        p_cierre.setLayout(p_cierreLayout);
        p_cierreLayout.setHorizontalGroup(
            p_cierreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JL_cierre, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        p_cierreLayout.setVerticalGroup(
            p_cierreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JL_cierre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(p_cierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 20));

        p_barra.setBackground(new java.awt.Color(0, 0, 0));
        p_barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                p_barraMouseDragged(evt);
            }
        });
        p_barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                p_barraMousePressed(evt);
            }
        });

        javax.swing.GroupLayout p_barraLayout = new javax.swing.GroupLayout(p_barra);
        p_barra.setLayout(p_barraLayout);
        p_barraLayout.setHorizontalGroup(
            p_barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        p_barraLayout.setVerticalGroup(
            p_barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(p_barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 900, 20));

        JP_DERECHO.setBackground(new java.awt.Color(158, 189, 197));

        JP_TITULO.setBackground(new java.awt.Color(236, 234, 228));

        JL_INFO1.setBackground(new java.awt.Color(255, 255, 255));
        JL_INFO1.setFont(new java.awt.Font("Roboto Medium", 0, 30)); // NOI18N
        JL_INFO1.setForeground(new java.awt.Color(255, 0, 51));
        JL_INFO1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_INFO1.setText("USUARIOS");

        javax.swing.GroupLayout JP_TITULOLayout = new javax.swing.GroupLayout(JP_TITULO);
        JP_TITULO.setLayout(JP_TITULOLayout);
        JP_TITULOLayout.setHorizontalGroup(
            JP_TITULOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_TITULOLayout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(JL_INFO1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JP_TITULOLayout.setVerticalGroup(
            JP_TITULOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_TITULOLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JL_INFO1)
                .addContainerGap())
        );

        JL_CANTIDAD.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        JL_CANTIDAD.setText("Cantidad: ");

        txt_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidadActionPerformed(evt);
            }
        });

        JL_TIPO.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        JL_TIPO.setText("Tipo: ");

        JL_DESCRIPCION.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        JL_DESCRIPCION.setText("Descripción: ");

        JL_PRECIO.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        JL_PRECIO.setText("Precio Unitaro: ");

        JL_IMPORTE.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        JL_IMPORTE.setText("Importe: ");

        jb_registro.setText("Registrar");
        jb_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_registroActionPerformed(evt);
            }
        });

        jb_modificar.setText("Modificar");
        jb_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modificarActionPerformed(evt);
            }
        });

        jb_eliminar.setText("Eliminar");
        jb_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarActionPerformed(evt);
            }
        });

        JL_BUSCAR.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        JL_BUSCAR.setText("Ingresa ID del producto a buscar: ");

        txt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarActionPerformed(evt);
            }
        });

        jb_buscar.setText("Buscar");
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed(evt);
            }
        });

        jb_limpiar.setText("Limpiar");
        jb_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_limpiarActionPerformed(evt);
            }
        });

        JS_tabla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        JT_productos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        JT_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JS_tabla.setViewportView(JT_productos);

        javax.swing.GroupLayout JP_DERECHOLayout = new javax.swing.GroupLayout(JP_DERECHO);
        JP_DERECHO.setLayout(JP_DERECHOLayout);
        JP_DERECHOLayout.setHorizontalGroup(
            JP_DERECHOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_TITULO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JP_DERECHOLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(JP_DERECHOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_DERECHOLayout.createSequentialGroup()
                        .addComponent(JS_tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(JP_DERECHOLayout.createSequentialGroup()
                        .addGroup(JP_DERECHOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JL_BUSCAR)
                            .addGroup(JP_DERECHOLayout.createSequentialGroup()
                                .addGroup(JP_DERECHOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JL_TIPO)
                                    .addComponent(JL_DESCRIPCION)
                                    .addComponent(JL_CANTIDAD)
                                    .addComponent(JL_PRECIO)
                                    .addComponent(JL_IMPORTE))
                                .addGroup(JP_DERECHOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JP_DERECHOLayout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(JP_DERECHOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(JP_DERECHOLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(JP_DERECHOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_importe, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_DERECHOLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(JP_DERECHOLayout.createSequentialGroup()
                .addGroup(JP_DERECHOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_DERECHOLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jb_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(jb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(jb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JP_DERECHOLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jb_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(jb_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JP_DERECHOLayout.setVerticalGroup(
            JP_DERECHOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_DERECHOLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JP_TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(JP_DERECHOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_CANTIDAD))
                .addGap(36, 36, 36)
                .addGroup(JP_DERECHOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_TIPO)
                    .addComponent(txt_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(JP_DERECHOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_DESCRIPCION)
                    .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(JP_DERECHOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_PRECIO))
                .addGap(33, 33, 33)
                .addGroup(JP_DERECHOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_importe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_IMPORTE))
                .addGap(30, 30, 30)
                .addGroup(JP_DERECHOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_modificar)
                    .addComponent(jb_registro)
                    .addComponent(jb_eliminar))
                .addGap(32, 32, 32)
                .addGroup(JP_DERECHOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_BUSCAR))
                .addGap(31, 31, 31)
                .addGroup(JP_DERECHOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_limpiar)
                    .addComponent(jb_buscar))
                .addGap(33, 33, 33)
                .addComponent(JS_tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(JP_DERECHO, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 700, 820));

        JP_IZQUIERDO.setBackground(new java.awt.Color(236, 234, 228));

        JL_logo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JL_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N

        JL_INFO.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        JL_INFO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_INFO.setText("Información");
        JL_INFO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_INFOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JL_INFOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JL_INFOMouseExited(evt);
            }
        });

        JL_USUARIOS.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        JL_USUARIOS.setForeground(new java.awt.Color(255, 0, 51));
        JL_USUARIOS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_USUARIOS.setText("Usuarios");
        JL_USUARIOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_USUARIOSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JL_USUARIOSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JL_USUARIOSMouseExited(evt);
            }
        });

        JL_EQUIPO.setFont(new java.awt.Font("Roboto Light", 2, 11)); // NOI18N
        JL_EQUIPO.setForeground(new java.awt.Color(102, 102, 102));
        JL_EQUIPO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_EQUIPO.setText("KAREN OLVERA & ISAAC PÉREZ");

        JL_UPI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/upi.png"))); // NOI18N

        JL_IPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/poli.png"))); // NOI18N

        JL_SALIR.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        JL_SALIR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_SALIR.setText("Salir");
        JL_SALIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_SALIRMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JL_SALIRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JL_SALIRMouseExited(evt);
            }
        });

        javax.swing.GroupLayout JP_IZQUIERDOLayout = new javax.swing.GroupLayout(JP_IZQUIERDO);
        JP_IZQUIERDO.setLayout(JP_IZQUIERDOLayout);
        JP_IZQUIERDOLayout.setHorizontalGroup(
            JP_IZQUIERDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_IZQUIERDOLayout.createSequentialGroup()
                .addGroup(JP_IZQUIERDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_IZQUIERDOLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JL_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JP_IZQUIERDOLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(JS_1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JP_IZQUIERDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JL_EQUIPO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JP_IZQUIERDOLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(JP_IZQUIERDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(JP_IZQUIERDOLayout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(JS_2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(JL_INFO, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JL_USUARIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(JP_IZQUIERDOLayout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addGroup(JP_IZQUIERDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JL_SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(JP_IZQUIERDOLayout.createSequentialGroup()
                                            .addComponent(JL_IPN)
                                            .addGap(35, 35, 35)
                                            .addComponent(JL_UPI)))))))
                    .addGroup(JP_IZQUIERDOLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(JS_3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        JP_IZQUIERDOLayout.setVerticalGroup(
            JP_IZQUIERDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_IZQUIERDOLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(JL_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(JL_INFO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JS_1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(JL_USUARIOS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JS_2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(JL_SALIR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JS_3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                .addGroup(JP_IZQUIERDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JL_IPN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_UPI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JL_EQUIPO, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        getContentPane().add(JP_IZQUIERDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JL_cierreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_cierreMouseClicked
        System.exit(0);
    }//GEN-LAST:event_JL_cierreMouseClicked

    private void JL_cierreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_cierreMouseEntered
        p_cierre.setBackground(java.awt.Color.RED);
        JL_cierre.setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_JL_cierreMouseEntered

    private void JL_cierreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_cierreMouseExited
        //p_cierre.setBackground(new java.awt.Color(236, 234, 228, 255));
        p_cierre.setBackground(java.awt.Color.BLACK);
        JL_cierre.setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_JL_cierreMouseExited

    private void p_barraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_barraMouseDragged
        int x= evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_p_barraMouseDragged

    private void p_barraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_barraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_p_barraMousePressed

    private void txt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidadActionPerformed

    private void jb_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_registroActionPerformed
        try{
            //rutaynombreBD/nombreUsuarioBD/contraseñaBD
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("insert into productos values(?,?,?,?,?,?)");
            //enviamos los campos a la base de datos
            pst.setString(1, "0");
            //quita espacios del inicio y final de la cadena
            pst.setString(2, txt_cantidad.getText().trim());
            pst.setString(3, txt_tipo.getText().trim());
            pst.setString(4, txt_descripcion.getText().trim());
            pst.setString(5, txt_precio.getText().trim());
            pst.setString(6, txt_importe.getText().trim());

            //indicamos que se ejecuten
            pst.executeUpdate();

            //limpiamos campos para los txt
            txt_cantidad.setText("");
            txt_tipo.setText("");
            txt_descripcion.setText("");
            txt_precio.setText("");
            txt_importe.setText("");
            JOptionPane.showMessageDialog(this, "PRODUCTO REGISTRADO CON ÉXITO");

        }catch (Exception e){

        }
    }//GEN-LAST:event_jb_registroActionPerformed

    private void jb_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed
        try{
            Connection cn = Conexion.conectar();
            //* significa que seleccione todo ---importante la ortagrafia, deben coincidir los nombres
            PreparedStatement pst = cn.prepareStatement("select * from productos where ID =?");
            pst.setString(1, txt_buscar.getText().trim());

            //obtenemos resultado de la busqueda
            ResultSet rs = pst.executeQuery();
//Busqueda por el ID
            //validacion de valores
            if(rs.next()){
                //si sucede brinca al siguiente paso
                txt_cantidad.setText(rs.getString("Cantidad"));
                txt_tipo.setText(rs.getString("Tipo"));
                txt_descripcion.setText(rs.getString("Descripcion"));
                txt_precio.setText(rs.getString("PrecioU"));
                txt_importe.setText(rs.getString("Importe"));
            }else{
               JOptionPane.showMessageDialog(this, "No se encuentra el producto.");
            }

        }catch (Exception e){

        }
    }//GEN-LAST:event_jb_buscarActionPerformed

    private void jb_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_limpiarActionPerformed

        txt_cantidad.setText("");
        txt_tipo.setText("");
        txt_descripcion.setText("");
        txt_precio.setText("");
        txt_importe.setText("");
        txt_buscar.setText("");
        //lb_estatus.setText(" ");

    }//GEN-LAST:event_jb_limpiarActionPerformed

    private void JL_USUARIOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_USUARIOSMouseClicked
        Usuarios cambioUser = new Usuarios(); 
            cambioUser.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_JL_USUARIOSMouseClicked

    private void JL_USUARIOSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_USUARIOSMouseEntered
        JL_USUARIOS.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_JL_USUARIOSMouseEntered

    private void JL_USUARIOSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_USUARIOSMouseExited
        JL_USUARIOS.setForeground(java.awt.Color.RED);
    }//GEN-LAST:event_JL_USUARIOSMouseExited

    private void JL_INFOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_INFOMouseClicked
        Informacion cambio = new Informacion(); 
            cambio.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_JL_INFOMouseClicked

    private void JL_INFOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_INFOMouseEntered
        JL_INFO.setForeground(java.awt.Color.RED);
    }//GEN-LAST:event_JL_INFOMouseEntered

    private void JL_INFOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_INFOMouseExited
        JL_INFO.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_JL_INFOMouseExited

    private void JL_SALIRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_SALIRMouseClicked
        Login cambioL = new Login();
        cambioL.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JL_SALIRMouseClicked

    private void JL_SALIRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_SALIRMouseEntered
        JL_SALIR.setForeground(java.awt.Color.RED);
    }//GEN-LAST:event_JL_SALIRMouseEntered

    private void JL_SALIRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_SALIRMouseExited
        JL_SALIR.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_JL_SALIRMouseExited

    private void jb_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modificarActionPerformed
      
    try{
       String ID = txt_buscar.getText().trim();
       Connection cn = Conexion.conectar();
       PreparedStatement pst = cn.prepareStatement("update productos set Cantidad = ?, Tipo = ?, Descripcion = ?, PrecioU = ?, Importe = ? where ID = " + ID);
    
       pst.setString(1, txt_cantidad.getText().trim());
       pst.setString(2, txt_tipo.getText().trim());
       pst.setString(3, txt_descripcion.getText().trim());
       pst.setString(4, txt_precio.getText().trim());
       pst.setString(5, txt_importe.getText().trim());
    
       pst.executeUpdate();
     JOptionPane.showMessageDialog(this,"MODICICACIÓN EXITOSA");
    }catch (Exception e) {     
    }
// TODO add your handling code here:
    }//GEN-LAST:event_jb_modificarActionPerformed

    private void jb_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarActionPerformed
        
        try{
       Connection cn = Conexion.conectar();
       PreparedStatement pst = cn.prepareStatement("delete from productos where ID = ?");
    
       pst.setString(1, txt_buscar.getText().trim());
       pst.executeUpdate();
      
       txt_cantidad.setText("");
       txt_tipo.setText("");
       txt_descripcion.setText("");
       txt_precio.setText("");
       txt_importe.setText("");
       JOptionPane.showMessageDialog(this, "ELIMINANCION EXITOSA");
        }catch (Exception e) {
            
        }

    }//GEN-LAST:event_jb_eliminarActionPerformed

    private void txt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL_BUSCAR;
    private javax.swing.JLabel JL_CANTIDAD;
    private javax.swing.JLabel JL_DESCRIPCION;
    private javax.swing.JLabel JL_EQUIPO;
    private javax.swing.JLabel JL_IMPORTE;
    private javax.swing.JLabel JL_INFO;
    private javax.swing.JLabel JL_INFO1;
    private javax.swing.JLabel JL_IPN;
    private javax.swing.JLabel JL_PRECIO;
    private javax.swing.JLabel JL_SALIR;
    private javax.swing.JLabel JL_TIPO;
    private javax.swing.JLabel JL_UPI;
    private javax.swing.JLabel JL_USUARIOS;
    private javax.swing.JLabel JL_cierre;
    private javax.swing.JLabel JL_logo;
    private javax.swing.JPanel JP_DERECHO;
    private javax.swing.JPanel JP_IZQUIERDO;
    private javax.swing.JPanel JP_TITULO;
    private javax.swing.JSeparator JS_1;
    private javax.swing.JSeparator JS_2;
    private javax.swing.JSeparator JS_3;
    private javax.swing.JScrollPane JS_tabla;
    private javax.swing.JTable JT_productos;
    private javax.swing.JButton jb_buscar;
    private javax.swing.JButton jb_eliminar;
    private javax.swing.JButton jb_limpiar;
    private javax.swing.JButton jb_modificar;
    private javax.swing.JButton jb_registro;
    private javax.swing.JPanel p_barra;
    private javax.swing.JPanel p_cierre;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_importe;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_tipo;
    // End of variables declaration//GEN-END:variables
}
